### ISSUE TITLE
Error: Could not find Chrome when deployed to Google Cloud

### ISSUE THREAD

**Issue by orestesgaolin** [jsreport/jsreport-gcloud-functions-starter-kit#2]
I've followed the tutorial but when calling the endpoint deployed to Google Cloud I'm getting following error:

```
 curl -m 70 -X POST https://europe-west1-xxx.cloudfunctions.net/jsreport -H "Authorization: bearer $(gcloud auth print-identity-token)" -H "Content-Type: application/json" -d '{  "template": {  "name": "health_report"  },  "data": {  "name": "John",  "start-date": "10 Aug 2022",  "end-date": "30 Aug 2023",  "year-of-birth": "1980"  } }'
Error: Could not find Chrome (ver. 114.0.5735.90). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.Error: Could not find Chrome (ver. 114.0.5735.90). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:304:27)
    at ChromeLauncher.executablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:180:25)
    at ChromeLauncher.computeLaunchArguments (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:37)
    at async ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:83:28)
    at async createBrowser (/workspace/node_modules/@jsreport/jsreport-chrome-pdf/lib/chromePoolStrategy.js:98:26)
    at async allocateBrowser (/workspace/node_modules/@jsreport/jsreport-chrome-pdf/lib/chromePoolStrategy.js:113:5)
    at async getBrowser (/workspace/node_modules/@jsreport/jsreport-chrome-pdf/lib/chromePoolStrategy.js:23:30)
    at async module.exports (/workspace/node_modules/@jsreport/jsreport-chrome-pdf/lib/conversion.js:11:19)
    at async execute (/workspace/node_modules/@jsreport/jsreport-chrome-pdf/lib/chromePoolStrategy.js:20:22)
    at async /workspace/node_modules/@jsreport/jsreport-chrome-pdf/lib/lazyRecipe.js:73:20dominik@cloudshell:
```

Running the server locally and calling the localhost endpoint works correctly.

When building the following entries can be seen in the log:

```
Error: Process exited with code 16
    at process.<anonymous> (/workspace/node_modules/@google-cloud/functions-framework/build/src/invoker.js:92:22)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.processEmit [as emit] (/workspace/node_modules/signal-exit/index.js:191:37)
    at process.exit (node:internal/process/per_thread:192:15)
    at sendCrashResponse (/workspace/node_modules/@google-cloud/functions-framework/build/src/logger.js:44:9)
    at process.<anonymous> (/workspace/node_modules/@google-cloud/functions-framework/build/src/invoker.js:88:44)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.processEmit [as emit] (/workspace/node_modules/signal-exit/index.js:199:34)

Error: Timeout occurred when waiting for the worker action "init"
    at Timeout._onTimeout (/workspace/node_modules/@jsreport/advanced-workers/lib/threadWorker.js:42:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Unhandled rejection
at process.processTimers (node:internal/timers:512:7)
 at listOnTimeout (node:internal/timers:569:17)
    at Timeout._onTimeout (/workspace/node_modules/@jsreport/advanced-workers/lib/threadWorker.js:42:23)

2023-08-25T09:56:19.006Z - [31merror[39m: Error occurred during reporter init: Error: Timeout occurred when waiting for the worker action "init"
2023-08-25T09:55:48.304Z - [34mdebug[39m: Extensions in workers: base, child-templates, components, data, handlebars, jsrender, localization, npm, pdf-utils, reports, text, assets, browser-client, chrome-pdf, docx, html-to-xlsx, pptx, scripts, static-pdf, xlsx
```

My package.json:

```json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "deploy": "gcloud services enable run.googleapis.com&&gcloud functions deploy jsreport --memory=1024M --gen2 --region=europe-west1 --runtime=nodejs18 --source=. --entry-point=jsreport --trigger-http",
    "gcp-build": "node node_modules/puppeteer/install.js"
  },
  "engines": {
    "node": "18"
  },
  "main": "index.js",
  "dependencies": {
    "@google-cloud/functions-framework": "^3.3.0",
    "fs-extra": "^11.1.1",
    "jsreport": "^3.13.0"
  },
  "devDependencies": {
    "eslint": "^8.15.0",
    "eslint-config-google": "^0.14.0",
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}
```

- Config and other files were unchanged. 
- I only added my own template.
- I run `npm install` before
- maybe there's some issue with puppeteer installtion?

Do you see any obvious issues with the given setup?

**Comment by orestesgaolin** [comment]
Following [this tutorial](https://hume.dev/articles/puppeteer-google-cloud-functions-v2/) helped me solve the issue. I also had to `npm install puppeteer`, so that this is the final package.json:

```json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "deploy": "gcloud services enable run.googleapis.com&&gcloud functions deploy jsreport --memory=1024M --gen2 --region=europe-west1 --runtime=nodejs18 --source=. --entry-point=jsreport --trigger-http",
    "gcp-build": "node node_modules/puppeteer/install.js"
  },
  "engines": {
    "node": "18"
  },
  "main": "index.js",
  "dependencies": {
    "@google-cloud/functions-framework": "^3.3.0",
    "fs-extra": "^11.1.1",
    "jsreport": "^3.13.0",
    "puppeteer": "^21.1.0"
  },
  "devDependencies": {
    "eslint": "^8.15.0",
    "eslint-config-google": "^0.14.0",
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}
```
